name: Build Plugin ZIP

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version
        id: version
        run: |
          VERSION=$(grep "Version:" roxy-show-tickets.php | head -1 | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "PLUGIN=roxy-show-tickets" >> $GITHUB_ENV

      - name: Build folder
        run: |
          mkdir build
          mkdir build/$PLUGIN
          rsync -av ./ build/$PLUGIN \
            --exclude '.git/' \
            --exclude '.github/' \
            --exclude 'build/' \
            --exclude '*.zip'

      - name: Create ZIP
        run: |
          cd build
          zip -r ${PLUGIN}-${VERSION}.zip $PLUGIN

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLUGIN }}-${{ env.VERSION }}
          path: build/${{ env.PLUGIN }}-${{ env.VERSION }}.zip

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/${{ env.PLUGIN }}-${{ env.VERSION }}.zip
          generate_release_notes: true
